### ISSUE TITLE
Arrived from the G+ Group 

### ISSUE THREAD

**Issue by TonyHine** [brucemcpherson/desktopliberation#1]
Well I've never used GitHub before, Just can't get my head around it!  So I'm here for two things, to be liberated by Bruce, and learn how to use GitHub! Looking forward to engaging in the community.

**Comment by brucemcpherson** [comment]
Hi Tony
Welcome, and thanks for signing up. I'm not sure exactly how this is going to work out, but there's lots of good capabilities on github, and since all my software is here anyway, it seems like a good choice. 

I havent exactly decided the workflow here yet, but we'll do something with labels and closing to keep the issues list relevant. Right now I wont close anything, but will make this as a conversation rather than an issue

cheers
